### ISSUE TITLE
应用安装程序无法安装包相关项

### ISSUE THREAD

**Issue by iKineticate** [YexuanXiao/PlayerWinRT#1]
你好！安装好证书后，安装应用时出现如图的问题

设备：Windows11 on ARM
版本：23H2 22631.3155

![image](https://github.com/YexuanXiao/PlayerWinRT/assets/115683118/44cee6b5-b210-4d0a-8177-79750a544ff9)

**Comment by YexuanXiao** [comment]
应该是因为我打包的比较早，所以不兼容了，重新编译打包就可以安装。

**Comment by iKineticate** [comment]
> 应该是因为我打包的比较早，所以不兼容了，重新编译打包就可以安装。

找到原因了，需要安装实验版本（Experimental releases）的Windows App SDK 1.4 Experimental1
我的电脑是稳定版（正式版）Windwos App SDK 1.4

![1fd5d3cbe97d955ca162c284fa4f0768](https://github.com/YexuanXiao/PlayerWinRT/assets/115683118/60d7e983-186d-4e40-8edf-5170b20dfd7d)

**Comment by YexuanXiao** [comment]
> > 应该是因为我打包的比较早，所以不兼容了，重新编译打包就可以安装。
> 
> 找到原因了，需要安装实验版本（Experimental releases）的Windows App SDK 1.4 Experimental1 我的电脑是稳定版（正式版）Windwos App SDK 1.4
> 
> ![1fd5d3cbe97d955ca162c284fa4f0768](https://private-user-images.githubusercontent.com/115683118/314505908-60d7e983-186d-4e40-8edf-5170b20dfd7d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NTIwODEsIm5iZiI6MTcxMDk1MTc4MSwicGF0aCI6Ii8xMTU2ODMxMTgvMzE0NTA1OTA4LTYwZDdlOTgzLTE4NmQtNGU0MC04ZWRmLTUxNzBiMjBkZmQ3ZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNjIzMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOWRjMDNiYTBjMjY1NzA4YmY1ODBmY2I5YjAyZTg0ZmJmNDA5N2EzZTE3YzYwZmMyYzMyNjQwMjkwZDI5YWQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.cVFx8v1zXYhAMN_WEmd76Nq-TLvO6_B9IQGMVlE6cZE)

最好用1.3编译，1.4开始有BUG会导致MenuFlyout不响应鼠标单击，看我另一个issue。
