### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by kavindren** [YexuanXiao/PlayerWinRT#5]
Hi. Im trying to compile the source code using VS2022 CE With WAS 1.3. During compilation tons of errors occur in file src/Pages/FolderView.xaml.cpp: E2486 invalid literal suffix "uz"; could not find literal operator or literal operator template "operator""uz" (line 179 and 20 more lines). Any solution?

**Comment by kavindren** [comment]
Solved by deleting every "z" on those lines (e. g. 1uz -> 1u)

**Comment by YexuanXiao** [comment]
The uz suffix for integer literals is a feature in C++23 that I really like. Unfortunately, MSVC hasn’t implemented it yet, so I created a patch in pch.h. If you include pch.h correctly, it should work fine (though it might give a one-time warning). Have you done anything else? If the project is being built as-is, I think this is an issue worth investigating.

**Comment by kavindren** [comment]
> The uz suffix for integer literals is a feature in C++23 that I really like. Unfortunately, MSVC hasn’t implemented it yet, so I created a patch in pch.h. If you include pch.h correctly, it should work fine (though it might give a one-time warning). Have you done anything else? If the project is being built as-is, I think this is an issue worth investigating.


Nope, I didn't do anything else. Just downloaded source code, tried to build it (Debug x64) and errors occured.
