### ISSUE TITLE
标题栏自定义

### ISSUE THREAD

**Issue by Endredaol** [YexuanXiao/PlayerWinRT#6]
请问标题栏可交互控件是怎么做的

**Comment by YexuanXiao** [comment]
标题栏三个按钮以及三个按钮左侧的位置默认是不可使用的，WAS提供了兼容Windows10的Window.SetTitleBar（应该是这个名）让这个区域缩小到就剩三个按钮以及三个按钮左侧的一点点区域，然后Window的内容就会上浮到标题栏，这时自己处理就行；以及仅限Windows11的AppWindow，后者和前者有类似效果，但是可以定义三个按钮的高度和颜色，并且需要手动计算可拖拽区域（用于移动窗口），并且需要自己处理标题栏的DPI，微软的文档有比较全的介绍。你可以参考我另一个仓库Authorization，这个仓库只完成了标题栏的自定义没有其他代码。

**Comment by endredaol** [comment]
一直没弄好，换成WAS1.6的TitleBar控件l

**Comment by Endredaol** [comment]
一直没弄好，换成了WAS1.6的TitleBar控件

**Comment by YexuanXiao** [comment]
> 一直没弄好，换成了WAS1.6的TitleBar控件

https://github.com/YexuanXiao/Authenticator

**Comment by Endredaol** [comment]
> > 一直没弄好，换成了WAS1.6的TitleBar控件
> 
> https://github.com/YexuanXiao/Authenticator

auto titleBar{ window_.TitleBar() };是怎么得到标题栏的

**Comment by YexuanXiao** [comment]
> > > 一直没弄好，换成了WAS1.6的TitleBar控件
> > 
> > https://github.com/YexuanXiao/Authenticator
> 
> auto titleBar{ window_.TitleBar() };是怎么得到标题栏的

Window.idl里暴露出来的
